export const WEBSOCKET_MESSAGE_TYPE = {
  STATE_CHANGED: 'stateChanged',
  CLIENT_CONNECTED: 'clientConnected',
  CLIENT_LOST: 'clientLost',
  GENERATION_RESULT: 'generationResult'
};

export const ACTION_KEYS = {
  CLIENT_CONNECTED: 'socket.' + WEBSOCKET_MESSAGE_TYPE.CLIENT_CONNECTED,
  CLIENT_LOST: 'socket.' + WEBSOCKET_MESSAGE_TYPE.CLIENT_LOST,
  STATE_CHANGED: 'socket.' + WEBSOCKET_MESSAGE_TYPE.STATE_CHANGED,
  GENERATION_RESULT: 'socket.' + WEBSOCKET_MESSAGE_TYPE.GENERATION_RESULT
};
