export const WEBSOCKET_MESSAGE_TYPE = {
  STATE_CHANGED: 'stateChanged',
  WORKER_CONNECTED: 'workerConnected',
  WORKER_LOST: 'workerLost',
  GENERATION_RESULT: 'generationResult'
};

export const ACTION_KEYS = {
  WORKER_CONNECTED: 'socket.' + WEBSOCKET_MESSAGE_TYPE.WORKER_CONNECTED,
  WORKER_LOST: 'socket.' + WEBSOCKET_MESSAGE_TYPE.WORKER_LOST,
  STATE_CHANGED: 'socket.' + WEBSOCKET_MESSAGE_TYPE.STATE_CHANGED,
  GENERATION_RESULT: 'socket.' + WEBSOCKET_MESSAGE_TYPE.GENERATION_RESULT
};
